#PYTHON APP 1
#PYTHON APP POD
apiVersion: v1 
kind: Pod   
metadata: 
  name: app1-pod
  labels:
    app: app1
spec: 
  containers:
  - name: app1-container 
    image: docker.io/kenphung/app1:samplek8s3t2
    env:
    - name: SECRET_NAME
      value: "Ken"
    - name: FORWARD_TO_POD_2
      value: "http://app2-service:6000"
    ports: 
    - containerPort: 5000
---
#PYTHON APP 1
#PYTHON APP POD  
apiVersion: v1 
kind: Service 
metadata:
  name: app1-service
  labels: 
    app: app1
spec: 
  type: NodePort 
  ports: 
    - nodePort: 30001 
      port: 6000
      targetPort: 5000
  selector:
    app: app1
---
#PYTHON APP 2
#PYTHON APP POD
apiVersion: v1 
kind: Pod   
metadata: 
  name: app2-pod 
  labels:
    app: app2
spec: 
  containers:
  - name: app2-container 
    image: docker.io/kenphung/app2:samplek8s3t2
    env:
    - name: FORWARD_TO_POD_1
      value: "http://app1-service:6000"
    ports: 
    - containerPort: 5001
---
#PYTHON APP 2
#PYTHON APP POD  
apiVersion: v1 
kind: Service 
metadata:
  name: app2-service 
  labels: 
    app: app2
spec: 
  type: NodePort 
  ports: 
    - nodePort: 30002 
      port: 6000
      targetPort: 5001
  selector:
    app: app2
---

